const types = {
  bug: "./bug-type.png",
  dark: "./dark-type.png",
  dragon: "./dragon-type.png",
  electric: "./electric-type.png",
  fairy: "./fairy-type.png",
  fighting: "./fighting-type.png",
  fire: "./fire-type.png",
  flying: "./flying-type.png",
  ghost: "./ghost-type.png",
  grass: "./grass-type.png",
  ground: "./ground-type.png",
  ice: "./ice-type.png",
  normal: "./normal-type.png",
  psychic: "./psychic-type.png",
  rock: "./rock-type.png",
  steel: "./steel-type.png",
  water: "./water-type.png",
};
